/*
Copyright 2017 Gustavo Hoirisch.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	ecr_v1alpha1 "github.com/gugahoi/memento/pkg/apis/ecr/v1alpha1"
	versioned "github.com/gugahoi/memento/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gugahoi/memento/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/gugahoi/memento/pkg/client/listers/ecr/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ECRInformer provides access to a shared informer and lister for
// ECRs.
type ECRInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ECRLister
}

type eCRInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewECRInformer constructs a new informer for ECR type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewECRInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredECRInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredECRInformer constructs a new informer for ECR type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredECRInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MementoV1alpha1().ECRs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MementoV1alpha1().ECRs(namespace).Watch(options)
			},
		},
		&ecr_v1alpha1.ECR{},
		resyncPeriod,
		indexers,
	)
}

func (f *eCRInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredECRInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eCRInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ecr_v1alpha1.ECR{}, f.defaultInformer)
}

func (f *eCRInformer) Lister() v1alpha1.ECRLister {
	return v1alpha1.NewECRLister(f.Informer().GetIndexer())
}
