apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.memento.gugahoi.com
spec:
  group: memento.gugahoi.com
  version: v1alpha1
  names:
    kind: Registry
    plural: registries
  scope: Namespaced
