// +build !ignore_autogenerated

/*
Copyright 2017 Gustavo Hoirisch.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	registry "github.com/gugahoi/memento/pkg/apis/registry"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Registry_To_registry_Registry,
		Convert_registry_Registry_To_v1alpha1_Registry,
		Convert_v1alpha1_RegistryList_To_registry_RegistryList,
		Convert_registry_RegistryList_To_v1alpha1_RegistryList,
		Convert_v1alpha1_RegistrySpec_To_registry_RegistrySpec,
		Convert_registry_RegistrySpec_To_v1alpha1_RegistrySpec,
		Convert_v1alpha1_RegistryStatus_To_registry_RegistryStatus,
		Convert_registry_RegistryStatus_To_v1alpha1_RegistryStatus,
	)
}

func autoConvert_v1alpha1_Registry_To_registry_Registry(in *Registry, out *registry.Registry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RegistrySpec_To_registry_RegistrySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RegistryStatus_To_registry_RegistryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Registry_To_registry_Registry is an autogenerated conversion function.
func Convert_v1alpha1_Registry_To_registry_Registry(in *Registry, out *registry.Registry, s conversion.Scope) error {
	return autoConvert_v1alpha1_Registry_To_registry_Registry(in, out, s)
}

func autoConvert_registry_Registry_To_v1alpha1_Registry(in *registry.Registry, out *Registry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_registry_RegistrySpec_To_v1alpha1_RegistrySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_registry_RegistryStatus_To_v1alpha1_RegistryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_registry_Registry_To_v1alpha1_Registry is an autogenerated conversion function.
func Convert_registry_Registry_To_v1alpha1_Registry(in *registry.Registry, out *Registry, s conversion.Scope) error {
	return autoConvert_registry_Registry_To_v1alpha1_Registry(in, out, s)
}

func autoConvert_v1alpha1_RegistryList_To_registry_RegistryList(in *RegistryList, out *registry.RegistryList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Items = *(*[]registry.Registry)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_RegistryList_To_registry_RegistryList is an autogenerated conversion function.
func Convert_v1alpha1_RegistryList_To_registry_RegistryList(in *RegistryList, out *registry.RegistryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegistryList_To_registry_RegistryList(in, out, s)
}

func autoConvert_registry_RegistryList_To_v1alpha1_RegistryList(in *registry.RegistryList, out *RegistryList, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Items = *(*[]Registry)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_registry_RegistryList_To_v1alpha1_RegistryList is an autogenerated conversion function.
func Convert_registry_RegistryList_To_v1alpha1_RegistryList(in *registry.RegistryList, out *RegistryList, s conversion.Scope) error {
	return autoConvert_registry_RegistryList_To_v1alpha1_RegistryList(in, out, s)
}

func autoConvert_v1alpha1_RegistrySpec_To_registry_RegistrySpec(in *RegistrySpec, out *registry.RegistrySpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_RegistrySpec_To_registry_RegistrySpec is an autogenerated conversion function.
func Convert_v1alpha1_RegistrySpec_To_registry_RegistrySpec(in *RegistrySpec, out *registry.RegistrySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegistrySpec_To_registry_RegistrySpec(in, out, s)
}

func autoConvert_registry_RegistrySpec_To_v1alpha1_RegistrySpec(in *registry.RegistrySpec, out *RegistrySpec, s conversion.Scope) error {
	return nil
}

// Convert_registry_RegistrySpec_To_v1alpha1_RegistrySpec is an autogenerated conversion function.
func Convert_registry_RegistrySpec_To_v1alpha1_RegistrySpec(in *registry.RegistrySpec, out *RegistrySpec, s conversion.Scope) error {
	return autoConvert_registry_RegistrySpec_To_v1alpha1_RegistrySpec(in, out, s)
}

func autoConvert_v1alpha1_RegistryStatus_To_registry_RegistryStatus(in *RegistryStatus, out *registry.RegistryStatus, s conversion.Scope) error {
	out.ARN = in.ARN
	return nil
}

// Convert_v1alpha1_RegistryStatus_To_registry_RegistryStatus is an autogenerated conversion function.
func Convert_v1alpha1_RegistryStatus_To_registry_RegistryStatus(in *RegistryStatus, out *registry.RegistryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RegistryStatus_To_registry_RegistryStatus(in, out, s)
}

func autoConvert_registry_RegistryStatus_To_v1alpha1_RegistryStatus(in *registry.RegistryStatus, out *RegistryStatus, s conversion.Scope) error {
	out.ARN = in.ARN
	return nil
}

// Convert_registry_RegistryStatus_To_v1alpha1_RegistryStatus is an autogenerated conversion function.
func Convert_registry_RegistryStatus_To_v1alpha1_RegistryStatus(in *registry.RegistryStatus, out *RegistryStatus, s conversion.Scope) error {
	return autoConvert_registry_RegistryStatus_To_v1alpha1_RegistryStatus(in, out, s)
}
